name: worktree tbx-coding
on:
  #schedule:
  # - cron: '0 1 * * 1'  #  1am every monday
  push:
    branches:
    - tbx-coding
    paths-ignore:
    - '**/README.md'
jobs:
  coding_toolbox:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ github.token }}
        - uses: actions/checkout@v4
        - name: Toolbox Build
          run: make
        - name: Set up Git
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        - name: Commit and push README.md changes
          run: |
            git add README.md
            git commit -m "Update README.md from Makefile build" README.md
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
